services:

  sistemasprotoactor:
    container_name: sistemasprotoactor
    #image: docker.io/natbodocker/sistemasprotoactor:1.0
    image: sistemasprotoactor:1.0
    ports:
      - 8080:8080/tcp 
##    networks:
##      - iss-network

##networks:
##  iss-network:
##    external: true

## docker-compose -f sistemaSProtoactor.yaml  up down